### ISSUE TITLE
Precision issues

### ISSUE THREAD

**Issue by francescotaurone** [canbula/ieee754#2]
If you choose Quadruple precision, the mantissa portion of the number gets approximated after a certain number of bits.

As an example, the results for Quadruple precision from this converter (https://babbage.cs.qc.cuny.edu/IEEE-754/) are different from the one using the IEEE754 class.

Digging a bit in the methods, the approximation is related to the fact that building the mantissa multiplying by 2 makes the error due to the initial approximation of the floating point number larger and larger, until it affects the result of the mantissa computation.

I read that python and numpy do not handle particularly well high precision real numbers.

I had to employ gmpy2 for my needs, maybe it's worth having a look at it for future modifications to the class.

**Comment by canbula** [comment]
This issue is fixed with version 0.4, thanks for the feedback.
https://github.com/canbula/ieee754/releases/tag/v_04
