### ISSUE TITLE
Inaccurate results for 0.5 and 0.75 for half-precision.

### ISSUE THREAD

**Issue by akincan-kilic** [canbula/ieee754#3]
For 0.5 by using [this tool](https://evanw.github.io/float-toy/), you can find the accurate IEEE754 Half Precision representation for 0.5 as follows: 
![image](https://user-images.githubusercontent.com/65862487/203164079-582edd7f-9203-471a-a110-c9e8d925c104.png)
But in this repo, we have:
![image](https://user-images.githubusercontent.com/65862487/203164174-9ea4f043-33ca-42b7-8b6c-c39e53e1e4f3.png)
This is inaccurate by 2 bits.

**Comment by canbula** [comment]
This issue is fixed with version 0.4, thanks for the feedback.
https://github.com/canbula/ieee754/releases/tag/v_04
