### ISSUE TITLE
Require python3.9+

### ISSUE THREAD

**Issue by stevobailey** [canbula/ieee754#4]
https://github.com/canbula/ieee754/blob/f193095f020c2a553bcad879bd5f22eb3c1ffeb4/ieee754/IEEE754.py#L200

Using list[str] as a return type requires python3.9 or greater. But I was able to install this on python3.6.

**Comment by canbula** [comment]
Thanks, you are right. The annotation `list[str]` is not really necessary for the functionality of the code. I will remove this part to ensure the compatibility with the older versions.

**Comment by canbula** [comment]
Solved with v0.11
